variable "aws_region" {}
variable "image_tag" {}
variable "nginx_tag" {}
variable "env" {}
variable "gitlab_username" {}
variable "gitlab_access_token" {}
variable "NEXT_PUBLIC_WITH_ANALYTICS" {}
variable "NEXT_PUBLIC_CAPTCHA_V3_KEY" {}
variable "NEXT_PUBLIC_SSR_API_HOST" {}
variable "NEXT_PUBLIC_API_HOST" {}
variable "NEXT_PUBLIC_WITH_SENTRY" {}
variable "NEXT_PUBLIC_SENTRY_DSN" {}
