export { ReactComponent as DiscoveryIcon } from './discovery.svg'
export { ReactComponent as FeedIcon } from './feed.svg'
export { ReactComponent as FollowingIcon } from './following.svg'
export { ReactComponent as LovePlaceIcon } from './love-place.svg'
export { ReactComponent as RelocationIcon } from './relocation.svg'
