export { ReactComponent as ArrowDownIcon } from './arrow-down.svg'
export { ReactComponent as ArrowLeftIcon } from './arrow-left.svg'
export { ReactComponent as AvatarIcon } from './avatar.svg'
export { ReactComponent as AvatarColorizedIcon } from './avatar-colorized.svg'
export { ReactComponent as BigPlusIcon } from './bigPlus.svg'
export { ReactComponent as CameraIcon } from './camera.svg'
export { ReactComponent as CareersIcon } from './careers.svg'
export { ReactComponent as CheckmarkIcon } from './checkmark.svg'
export { ReactComponent as CrossIcon } from './close.svg'
export { ReactComponent as CommentsCounterIcon } from './comments-counter.svg'
export { ReactComponent as CoverIcon } from './cover.svg'
export { ReactComponent as CoverColorizedIcon } from './cover-colorized.svg'
export { ReactComponent as CrossInCircleIcon } from './cross-in-circle.svg'
export { ReactComponent as DeleteSubTaskIcon } from './delete-sub-task.svg'
export { ReactComponent as DeleteTaskIcon } from './delete-task.svg'
export { ReactComponent as DoneIcon } from './done.svg'
export { ReactComponent as EditProfileIcon } from './edit-profile.svg'
export { ReactComponent as FavoriteEmptyIcon } from './favorite-empty.svg'
export { ReactComponent as FavoriteFillIcon } from './favorite-fill.svg'
export { ReactComponent as FavoriteMarkerRedIcon } from './favorite-marker-red.svg'
export { ReactComponent as FavoriteMarkerWhiteIcon } from './favorite-marker-white.svg'
export { AllowLocationSettingsImage, NewYorkImage } from './landing'
export { ReactComponent as LocationIcon } from './location.svg'
export { ReactComponent as LogoutIcon } from './log-out.svg'
export { ReactComponent as LoginPageIllustration } from './login-page-illustration.svg'
export { ReactComponent as LovePlanetBlueIcon } from './love-planet-blue.svg'
export { LovePlanetAreaIcon } from './LovePlanetAreaIcon'
export { ReactComponent as MapIcon } from './map.svg'
export { ReactComponent as MessagesColorized } from './messages-colorized.svg'
export { ReactComponent as MinusIcon } from './minus.svg'
export { ReactComponent as MockWithActionImage } from './mock-with-action.svg'
export { ReactComponent as LovePlaceIcon } from './navigation/love-place.svg'
export { ReactComponent as NewYorkIcon } from './new-york.svg'
export { ReactComponent as PlaceholderAuth } from './placeholders/placeholder-auth.svg'
export { ReactComponent as PlaceholderBubbles } from './placeholders/placeholder-bubbles.svg'
export { ReactComponent as PlaceholderEye } from './placeholders/placeholder-eye.svg'
export { ReactComponent as PlaceholderMarker } from './placeholders/placeholder-marker.svg'
export { ReactComponent as PlaceholderQuestion } from './placeholders/placeholder-question.svg'
export { ReactComponent as PlaceholderSuccessfulApplication } from './placeholders/placeholder-successful-application.svg'
export { PlanetGeoLocationIcon } from './PlanetGeoLocation'
export { ReactComponent as PlayIcon } from './play.svg'
export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as PrivacyPolicyIcon } from './privacy-policy.svg'
export { default as quizHistoryPlaceholder } from './quiz-history-placeholder.png'
export { default as quizHistoryPlaceholderMobile } from './quiz-history-placeholder-mobile.png'
export { ReactComponent as EditTodoIcon } from './relocation/edit-todo.svg'
export { ReactComponent as StartBannerImage } from './relocation/start-banner.svg'
export { ReactComponent as ReturnToActiveIcon } from './return-to-active.svg'
export { ReactComponent as SortIcon } from './sort.svg'
// //TODO: remove profile-copy.svg (same mask id conflicts)
export { ReactComponent as AddTodoPlusIcon } from './add-todo-plus.svg'
export { ReactComponent as AlertIcon } from './alert.svg'
export { ReactComponent as AllFiltersIcon } from './all-filters.svg'
export { ReactComponent as ArrowRight } from './arrow-right-white.svg'
export { ArrowIcon } from './ArrowIcon'
export { ReactComponent as BellIcon } from './bell.svg'
export { ReactComponent as CenteredMarker } from './centered-marker.svg'
export { ReactComponent as ChatIcon } from './chat.svg'
export { ReactComponent as CheckMarkInCircleIcon } from './check-mark-in-circle.svg'
export { ChevronIcon } from './ChevronIcon'
export { ChevronSmallIcon } from './ChevronSmallIcon'
export { ReactComponent as CommentsIcon } from './comments.svg'
export { ReactComponent as DemographicsIcon } from './demographics.svg'
export { ReactComponent as DescriptionIcon } from './description.svg'
export { ReactComponent as DiversityIcon } from './diversity.svg'
export { ReactComponent as DoneAlternativeIcon } from './done-alternative.svg'
export { ReactComponent as EditIcon } from './edit.svg'
export { ReactComponent as EditGradientIcon } from './edit-gradient.svg'
export { ReactComponent as EmailSupportIcon } from './email-support.svg'
export { ReactComponent as FollowingsIcon } from './followings.svg'
export { ReactComponent as GeoIcon } from './geo.svg'
export { ReactComponent as GeoSmallIcon } from './geo-small.svg'
export { ReactComponent as HousePricingIcon } from './house-pricing.svg'
export { ReactComponent as InfoIcon } from './info.svg'
export { ReactComponent as ListIcon } from './list.svg'
export { ReactComponent as LocationSmallIcon } from './location-small.svg'
export { ReactComponent as MarketIcon } from './market.svg'
export { ReactComponent as MediaIcon } from './media.svg'
export { ReactComponent as MoreIcon } from './more.svg'
export { ReactComponent as NeighborhoodIcon } from './neighbourhood.svg'
export { PlaceholderFeedIcon } from './PlaceholderFeed'
export { ReactComponent as PlaceholderBell } from './placeholders/placeholder-bell.svg'
export { ReactComponent as PlaceholderEarth } from './placeholders/placeholder-earth.svg'
export { ReactComponent as PlaceholderEmotions } from './placeholders/placeholder-emotions.svg'
export { ReactComponent as PlaceholderGear } from './placeholders/placeholder-gear.svg'
export { ReactComponent as PlaceholderHousesPlus } from './placeholders/placeholder-houses-plus.svg'
export { ReactComponent as PlaceholderUserPlus } from './placeholders/placeholder-user-plus.svg'
export { PlaceholderEyeIcon } from './placeholders/PlaceholderEyeIcon'
export { PlaceholderMarkerIcon } from './placeholders/PlaceholderMarkerIcon'
export { PlaceholderQuestionIcon } from './placeholders/PlaceholderQuestionIcon'
export { ReactComponent as PlayButtonIcon } from './play-button.svg'
export { ReactComponent as ProfileIcon } from './profile.svg'
export { ReactComponent as ProfileCopyIcon } from './profile-copy.svg'
export { ReactComponent as PropertyHomeIcon } from './property-home.svg'
export { ReactComponent as QuestionColorized } from './question-colorized.svg'
export { ReactComponent as RelocationProfessionalsIcon } from './relocation/professionals.svg'
export { ReactComponent as RelocationQuotesIcon } from './relocation/quotes.svg'
export { ReactComponent as RelocationSchedulingIcon } from './relocation/scheduling.svg'
export { ReactComponent as RelocationSupportIcon } from './relocation/support.svg'
export { ReactComponent as RelocationGuideIcon } from './relocation-guide.svg'
export { ReactComponent as ResetLandmarkWarningIcon } from './reset-landmark-warning-icon.svg'
export { ReactComponent as RoundedTriangularIcon } from './rounded-triangular.svg'
export * from './scoreEmoji'
export { ReactComponent as ScoresIcon } from './scores.svg'
export { ReactComponent as NothingFoundImg } from './search-nothing-found.svg'
export { ReactComponent as SearchServicesIcon } from './search-services.svg'
export { ReactComponent as SettingsIcon } from './settings-icon.svg'
export { ReactComponent as ShareIcon } from './share.svg'
export { ReactComponent as SharingImg } from './sharing-image.svg'
export { ReactComponent as SignUp } from './sign-up.svg'
export { ReactComponent as Spinner } from './spinner.svg'
export { ReactComponent as ThreeDotsIcon } from './three-dots.svg'
export { ReactComponent as TipLocationIcon } from './tip-location.svg'
export { ReactComponent as TooltipArrow } from './tooltip-arrow.svg'
export { ReactComponent as TooltipArrowCentered } from './tooltip-arrow-centered.svg'
export { ReactComponent as TransportAndProximityIcon } from './transport-and-proximity.svg'
export { ReactComponent as TransportAndProximity } from './transport-and-proximity.svg'
export { ReactComponent as TrashCanIcon } from './trash-can.svg'
export { ReactComponent as VerticalDotsIcon } from './vertical-dots.svg'
export { ReactComponent as WarningIcon } from './warning.svg'
export { ReactComponent as WhatLocalsSayIcon } from './what-locals-says.svg'
export { ReactComponent as WhiteHeartIcon } from './white-heart-icon.svg'
export { ReactComponent as ZoomInPlusIcon } from './zoom-in-plus-icon.svg'
export {
  ZoomCityIcon,
  ZoomNeighborhoodIcon,
  ZoomStateIcon,
  ZoomWorldIcon,
} from './zoom-levels'
export { ReactComponent as ZoomOutMinusIcon } from './zoom-out-minus-icon.svg'
